In [1]:
import pandas as pd
import csv

In [2]:
path = '../Downloads/productSecurityExchangeTypeMapping.csv'
df = pd.read_csv(path,delimiter='|')

In [3]:
df.head()

              productid securityExchange
0  16063438578467349077              EQU
1   3871264020596532388              EQU
2  15473751718583312885              EQU
3  15220361146149106549              EQU
4  13561718717741181427              EQU

In [4]:
df.loc[:, ['securityExchange']]

     securityExchange
0                 EQU
1                 EQU
2                 EQU
3                 EQU
4                 EQU
5                 EQU
6                 EQU
7                 EQU
8                 EQU
9                 EQU
10                EQU
11                EQU
12                EQU
13                EQU
14                EQU
15                EQU
16                EQU
17                EQU
18                EQU
19                EQU
20                EQU
21                EQU
22                EQU
23                EQU
24                EQU
25                EQU
26                EQU
27                EQU
28                EQU
29                EQU
...               ...
5537              EQU
5538              DER
5539              DER
5540              EQU
5541              EQU
5542              EQU
5543              EQU
5544              EQU
5545              EQU
5546              EQU
5547              EQU
5548              EQU
5549              EQU
5550              EQU
5551              EQU
5552              EQU
5553              EQU
5554              EQU
5555              EQU
5556              EQU
5557              EQU
5558              EQU
5559              EQU
5560              EQU
5561              EQU
5562              EQU
5563              EQU
5564              EQU
5565              DER
5566              DER

[5567 rows x 1 columns]

In [10]:
df.loc[:, 'secExchId'] = df.loc[:, 'securityExchange'].map({'EQU':'211', 'DER':'97'})

In [11]:
df.loc[:, ['productid','secExchId']]

                 productid secExchId
0     16063438578467349077       211
1      3871264020596532388       211
2     15473751718583312885       211
3     15220361146149106549       211
4     13561718717741181427       211
5     17276146493181720528       211
6     18050675640290990071       211
7      8728604934105447905       211
8     10821343002963919068       211
9     13641188918752535957       211
10    13412686788872065448       211
11    14989283557312339323       211
12     5104297335803653632       211
13     5819809776947978626       211
14    13282122225098549738       211
15      804783075167527974       211
16    12202984947702566456       211
17    15571714568803262223       211
18    13767675581426210706       211
19     6959986762119169196       211
20    14881217030399386110       211
21    11145720032900840139       211
22     1459793702974518211       211
23    17433009104274770823       211
24     4265562996896129944       211
25     7925543157792035543       211
26     3090935647850837756       211
27    13389319336815620990       211
28     5923520562044595272       211
29     6282695469991164296       211
...                    ...       ...
5537  14963955815988643979       211
5538   2989394268339299796        97
5539  16967597863212074952        97
5540  10800105921386326751       211
5541   1719741721995261745       211
5542   3795568430779206061       211
5543  17753290427347556121       211
5544  14555552413760569167       211
5545   1215876819693439923       211
5546  15609953998721569506       211
5547  16000598565453111264       211
5548    824719538472877355       211
5549   8837562526563942245       211
5550   5455169431109127073       211
5551  15155787094172432345       211
5552   8093877552817251730       211
5553  17130814320282352518       211
5554  10644426243576605315       211
5555   7990122878040829267       211
5556   2609659973908983028       211
5557  12535321040959300412       211
5558   4980738678221169902       211
5559    479141301416981168       211
5560  14138314720922077544       211
5561  11792701432185285338       211
5562   9996123464541040679       211
5563   1510724706580532108       211
5564   5739786577207025747       211
5565   2292380950259290378        97
5566   5950990417664627276        97

[5567 rows x 2 columns]

In [13]:
df.shape

(5567, 3)